spring.application.name=jps

spring.cassandra.keyspace-name=rastreio
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create-if-not-exists

app.public-url=http://localhost:4200
