spring:
  cassandra:
    keyspace-name: rastreio
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS

  security:
    user:
      name: ignored

jwt:
  secret: sua-chave-secreta-aqui-minimo-256-bits
  expiration: 900000      # 15 minutos em ms
  refresh-expiration: 604800000  # 7 dias em ms
